### PR TITLE
Add support for the new kirby format

### PR DESCRIPTION
**Pull request by casperisfine**
Ref: https://github.com/rubytogether/kirby/pull/20

In the new format, instead of a single integer per metric, we get an object such as `{"total": 1234, "unique": 12}`.

Note that `unique` is a daily unique from a single log file, so combining it over long period may not be super relevant, but given the current infrastructure, that's the best we can do, and it will still be more relevant that the current total.

This PR only do the log processing side, I don't think it's worth showing that data until we have enough data anyway.

Not sure if we'd want to process old logs, or just wait a while.

I added some tests to make it easier for me to develop this, somehow they are super flaky, not too sure why.

cc @indirect

### CODE REVIEW

**Comment by indirect** [comment]
Ah, of course, I didn't think of this before but each log file only includes logs for one hour, from one data center. So there are usually 24 (hours) * 38 (data centers) = 912 log files per day. So the worst case is that we might be counting a single client IP 912 times per day... but that's still a lot better than tens of thousands of times per day!

**Comment by indirect** [comment]
Yes, I think it's extremely likely that a single user will always hit the same POP, so maybe we should just call this "estimated hourly uniques" or something like that, rather than daily uniques, and then things are accurate. 👍🏻

**Comment by casperisfine** [comment]
I suppose we can keep it as `_unique` in the DB, might as well not have overly long keys for indexing purposes. It's more on the frontend that we may need to chose the proper label and maybe have some kind of explanation.

By the way, you think it will be possible to re-process historical data? Or is it complicated?

**Comment by indirect** [comment]
We have archives all the way back to (iirc) 2016, but the glacier access fees add up. My impression is that we could do the last 6-12 months fairly easily by writing a script that invokes the lambda for each file still in S3, and we could reindex all the way back to 2016 if we could convince AWS to give us ~$20k in credit.

**Comment by casperisfine** [comment]
> ~$20k in credit.

Ouch.

**Comment by indirect** [comment]
> Ouch.

Wow, that made me go look it up, and AWS has added new, _much_ cheaper Glacier retrieval options since the last time I checked! It might actually be as cheap as ~$2k now, if Lambda has also gotten cheaper since the last time I priced it out. 😄

**Comment by indirect** [comment]
Phew, got CI working via Actions, if you rebase you should pick it up.

I'm also seeing your tests seemingly randomly pass and fail when I try to run them locally, I really don't know what's going on there. 😬

**Comment by casperisfine** [comment]
Yeah, I'll dig into that. Seems like sometime not all stats are inserted, but it doesn't raise an error or anything.

And it's not a leaky test issue, because the same happen when running a single example.

**Comment by casperisfine** [comment]
Ok, I figured the problem. The fixture file contains two entries, and this app use UUID as primary keys, so `Model.last` isn't ordered like on a more vanilla Rails app.

Should be stable now.

**Comment by indirect** [comment]
Nice work!

**Pull request merged**
